// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace BanpoFri.Data
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct DrawFoodData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static DrawFoodData GetRootAsDrawFoodData(ByteBuffer _bb) { return GetRootAsDrawFoodData(_bb, new DrawFoodData()); }
  public static DrawFoodData GetRootAsDrawFoodData(ByteBuffer _bb, DrawFoodData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DrawFoodData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Foodidx { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool MutateFoodidx(int foodidx) { int o = __p.__offset(4); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, foodidx); return true; } else { return false; } }
  public int Drawfoodcount { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool MutateDrawfoodcount(int drawfoodcount) { int o = __p.__offset(6); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, drawfoodcount); return true; } else { return false; } }

  public static Offset<BanpoFri.Data.DrawFoodData> CreateDrawFoodData(FlatBufferBuilder builder,
      int foodidx = 0,
      int drawfoodcount = 0) {
    builder.StartTable(2);
    DrawFoodData.AddDrawfoodcount(builder, drawfoodcount);
    DrawFoodData.AddFoodidx(builder, foodidx);
    return DrawFoodData.EndDrawFoodData(builder);
  }

  public static void StartDrawFoodData(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddFoodidx(FlatBufferBuilder builder, int foodidx) { builder.AddInt(0, foodidx, 0); }
  public static void AddDrawfoodcount(FlatBufferBuilder builder, int drawfoodcount) { builder.AddInt(1, drawfoodcount, 0); }
  public static Offset<BanpoFri.Data.DrawFoodData> EndDrawFoodData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<BanpoFri.Data.DrawFoodData>(o);
  }
  public DrawFoodDataT UnPack() {
    var _o = new DrawFoodDataT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(DrawFoodDataT _o) {
    _o.Foodidx = this.Foodidx;
    _o.Drawfoodcount = this.Drawfoodcount;
  }
  public static Offset<BanpoFri.Data.DrawFoodData> Pack(FlatBufferBuilder builder, DrawFoodDataT _o) {
    if (_o == null) return default(Offset<BanpoFri.Data.DrawFoodData>);
    return CreateDrawFoodData(
      builder,
      _o.Foodidx,
      _o.Drawfoodcount);
  }
}

public class DrawFoodDataT
{
  [Newtonsoft.Json.JsonProperty("foodidx")]
  public int Foodidx { get; set; }
  [Newtonsoft.Json.JsonProperty("drawfoodcount")]
  public int Drawfoodcount { get; set; }

  public DrawFoodDataT() {
    this.Foodidx = 0;
    this.Drawfoodcount = 0;
  }
}


static public class DrawFoodDataVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Foodidx*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*Drawfoodcount*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
