// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace BanpoFri.Data
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct FoodMergeGroupData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static FoodMergeGroupData GetRootAsFoodMergeGroupData(ByteBuffer _bb) { return GetRootAsFoodMergeGroupData(_bb, new FoodMergeGroupData()); }
  public static FoodMergeGroupData GetRootAsFoodMergeGroupData(ByteBuffer _bb, FoodMergeGroupData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FoodMergeGroupData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Foodmergeidx { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool MutateFoodmergeidx(int foodmergeidx) { int o = __p.__offset(4); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, foodmergeidx); return true; } else { return false; } }
  public BanpoFri.Data.InGameFoodData? Ingamefooddatas(int j) { int o = __p.__offset(6); return o != 0 ? (BanpoFri.Data.InGameFoodData?)(new BanpoFri.Data.InGameFoodData()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int IngamefooddatasLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<BanpoFri.Data.FoodMergeGroupData> CreateFoodMergeGroupData(FlatBufferBuilder builder,
      int foodmergeidx = 0,
      VectorOffset ingamefooddatasOffset = default(VectorOffset)) {
    builder.StartTable(2);
    FoodMergeGroupData.AddIngamefooddatas(builder, ingamefooddatasOffset);
    FoodMergeGroupData.AddFoodmergeidx(builder, foodmergeidx);
    return FoodMergeGroupData.EndFoodMergeGroupData(builder);
  }

  public static void StartFoodMergeGroupData(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddFoodmergeidx(FlatBufferBuilder builder, int foodmergeidx) { builder.AddInt(0, foodmergeidx, 0); }
  public static void AddIngamefooddatas(FlatBufferBuilder builder, VectorOffset ingamefooddatasOffset) { builder.AddOffset(1, ingamefooddatasOffset.Value, 0); }
  public static VectorOffset CreateIngamefooddatasVector(FlatBufferBuilder builder, Offset<BanpoFri.Data.InGameFoodData>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateIngamefooddatasVectorBlock(FlatBufferBuilder builder, Offset<BanpoFri.Data.InGameFoodData>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateIngamefooddatasVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<BanpoFri.Data.InGameFoodData>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateIngamefooddatasVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<BanpoFri.Data.InGameFoodData>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartIngamefooddatasVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<BanpoFri.Data.FoodMergeGroupData> EndFoodMergeGroupData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<BanpoFri.Data.FoodMergeGroupData>(o);
  }
  public FoodMergeGroupDataT UnPack() {
    var _o = new FoodMergeGroupDataT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(FoodMergeGroupDataT _o) {
    _o.Foodmergeidx = this.Foodmergeidx;
    _o.Ingamefooddatas = new List<BanpoFri.Data.InGameFoodDataT>();
    for (var _j = 0; _j < this.IngamefooddatasLength; ++_j) {_o.Ingamefooddatas.Add(this.Ingamefooddatas(_j).HasValue ? this.Ingamefooddatas(_j).Value.UnPack() : null);}
  }
  public static Offset<BanpoFri.Data.FoodMergeGroupData> Pack(FlatBufferBuilder builder, FoodMergeGroupDataT _o) {
    if (_o == null) return default(Offset<BanpoFri.Data.FoodMergeGroupData>);
    var _ingamefooddatas = default(VectorOffset);
    if (_o.Ingamefooddatas != null) {
      var __ingamefooddatas = new Offset<BanpoFri.Data.InGameFoodData>[_o.Ingamefooddatas.Count];
      for (var _j = 0; _j < __ingamefooddatas.Length; ++_j) { __ingamefooddatas[_j] = BanpoFri.Data.InGameFoodData.Pack(builder, _o.Ingamefooddatas[_j]); }
      _ingamefooddatas = CreateIngamefooddatasVector(builder, __ingamefooddatas);
    }
    return CreateFoodMergeGroupData(
      builder,
      _o.Foodmergeidx,
      _ingamefooddatas);
  }
}

public class FoodMergeGroupDataT
{
  [Newtonsoft.Json.JsonProperty("foodmergeidx")]
  public int Foodmergeidx { get; set; }
  [Newtonsoft.Json.JsonProperty("ingamefooddatas")]
  public List<BanpoFri.Data.InGameFoodDataT> Ingamefooddatas { get; set; }

  public FoodMergeGroupDataT() {
    this.Foodmergeidx = 0;
    this.Ingamefooddatas = null;
  }
}


static public class FoodMergeGroupDataVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Foodmergeidx*/, 4 /*int*/, 4, false)
      && verifier.VerifyVectorOfTables(tablePos, 6 /*Ingamefooddatas*/, BanpoFri.Data.InGameFoodDataVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
